# Your Solution
version: '3'
services:
   
  book-library:
    image: books
    build: 
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: books
    ports:
     - "4200:4200"
    environment:
      - PORT=4200
      - DATABASE_URL=postgresql://sit722_9_2d_user:NvsakndxaZ8IP1iYYK08OOT98DQOtoPh@dpg-crpqoe0gph6c73a1lp3g-a.oregon-postgres.render.com/sit722_9_2d
    restart: "no"

  book-inventory:
    image: inventory
    build: 
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory
    ports:
     - "6001:6001"
    environment:
      - PORT=6001
      - DATABASE_URL=postgresql://sit722_9_2d_user:NvsakndxaZ8IP1iYYK08OOT98DQOtoPh@dpg-crpqoe0gph6c73a1lp3g-a.oregon-postgres.render.com/sit722_9_2d
    restart: "no"